name: fitmeta_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0 # Para fazer requisições HTTP à sua API
  shared_preferences: ^2.2.1 # Para armazenar o token JWT localmente no dispositivo
  flutter_dotenv: ^5.1.0 # Adicione esta linha


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
